-- Session 11: Partition rsa_ticket_locations + rsa_team_locations by month (Task 2.6)
--
-- Strategy: rename old table → create partitioned table with same name → copy data → RLS → indexes
-- Partition key: synced_at (timestamptz) RANGE by calendar month
-- PK becomes (id, synced_at) — partition key must be in PK
-- Old tables preserved as *_old for safety (drop after 1 week if all good)
--
-- Rollback:
--   DROP TABLE rsa_ticket_locations CASCADE;
--   DROP TABLE rsa_team_locations CASCADE;
--   ALTER TABLE rsa_ticket_locations_old RENAME TO rsa_ticket_locations;
--   ALTER TABLE rsa_team_locations_old RENAME TO rsa_team_locations;
--   SELECT cron.unschedule('create_monthly_location_partitions');
--   DROP FUNCTION IF EXISTS public.create_monthly_location_partitions();

-- ── 1. Rename existing tables ────────────────────────────────────────────────
ALTER TABLE rsa_ticket_locations RENAME TO rsa_ticket_locations_old;
ALTER TABLE rsa_team_locations   RENAME TO rsa_team_locations_old;
ALTER SEQUENCE IF EXISTS rsa_ticket_locations_id_seq RENAME TO rsa_ticket_locations_old_id_seq;
ALTER SEQUENCE IF EXISTS rsa_team_locations_id_seq   RENAME TO rsa_team_locations_old_id_seq;

-- ── 2. Create new partitioned tables ─────────────────────────────────────────
CREATE TABLE rsa_ticket_locations (
  id            bigint GENERATED BY DEFAULT AS IDENTITY,
  ticket_number text NOT NULL,
  status        text,
  lat           double precision NOT NULL,
  lng           double precision NOT NULL,
  synced_at     timestamptz NOT NULL,
  location      geography,
  PRIMARY KEY (id, synced_at)
) PARTITION BY RANGE (synced_at);

CREATE TABLE rsa_team_locations (
  id         bigint GENERATED BY DEFAULT AS IDENTITY,
  name       text NOT NULL,
  chassis    text NOT NULL,
  reg_number text NOT NULL,
  lat        double precision NOT NULL,
  lng        double precision NOT NULL,
  synced_at  timestamptz NOT NULL,
  location   geography,
  PRIMARY KEY (id, synced_at)
) PARTITION BY RANGE (synced_at);

-- ── 3. Monthly partitions (June + July + DEFAULT catch-all) ──────────────────
CREATE TABLE rsa_ticket_locations_2026_06 PARTITION OF rsa_ticket_locations
  FOR VALUES FROM ('2026-06-01') TO ('2026-07-01');
CREATE TABLE rsa_ticket_locations_2026_07 PARTITION OF rsa_ticket_locations
  FOR VALUES FROM ('2026-07-01') TO ('2026-08-01');
CREATE TABLE rsa_ticket_locations_default PARTITION OF rsa_ticket_locations DEFAULT;

CREATE TABLE rsa_team_locations_2026_06 PARTITION OF rsa_team_locations
  FOR VALUES FROM ('2026-06-01') TO ('2026-07-01');
CREATE TABLE rsa_team_locations_2026_07 PARTITION OF rsa_team_locations
  FOR VALUES FROM ('2026-07-01') TO ('2026-08-01');
CREATE TABLE rsa_team_locations_default PARTITION OF rsa_team_locations DEFAULT;

-- ── 4. Copy existing data ─────────────────────────────────────────────────────
INSERT INTO rsa_ticket_locations (id, ticket_number, status, lat, lng, synced_at, location)
  OVERRIDING SYSTEM VALUE
  SELECT id, ticket_number, status, lat, lng, synced_at, location
  FROM rsa_ticket_locations_old;

INSERT INTO rsa_team_locations (id, name, chassis, reg_number, lat, lng, synced_at, location)
  OVERRIDING SYSTEM VALUE
  SELECT id, name, chassis, reg_number, lat, lng, synced_at, location
  FROM rsa_team_locations_old;

-- ── 5. Reset sequences past max(id) ──────────────────────────────────────────
SELECT setval(
  pg_get_serial_sequence('rsa_ticket_locations', 'id'),
  (SELECT MAX(id) FROM rsa_ticket_locations)
);
SELECT setval(
  pg_get_serial_sequence('rsa_team_locations', 'id'),
  (SELECT MAX(id) FROM rsa_team_locations)
);

-- ── 6. RLS (same policy as old tables: authenticated read) ───────────────────
ALTER TABLE rsa_ticket_locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE rsa_team_locations   ENABLE ROW LEVEL SECURITY;

CREATE POLICY "authenticated_select" ON rsa_ticket_locations
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "authenticated_select" ON rsa_team_locations
  FOR SELECT TO authenticated USING (true);

-- ── 7. Indexes per partition ──────────────────────────────────────────────────
CREATE INDEX ON rsa_ticket_locations_2026_06 (synced_at);
CREATE INDEX ON rsa_ticket_locations_2026_07 (synced_at);
CREATE INDEX ON rsa_ticket_locations_default (synced_at);
CREATE INDEX ON rsa_ticket_locations_2026_06 (ticket_number);
CREATE INDEX ON rsa_ticket_locations_2026_07 (ticket_number);
CREATE INDEX ON rsa_ticket_locations_default (ticket_number);

CREATE INDEX ON rsa_team_locations_2026_06 (synced_at);
CREATE INDEX ON rsa_team_locations_2026_07 (synced_at);
CREATE INDEX ON rsa_team_locations_default (synced_at);

-- ── 8. Auto-partition function (runs on 25th of each month at 00:00 UTC) ─────
CREATE OR REPLACE FUNCTION public.create_monthly_location_partitions()
RETURNS void LANGUAGE plpgsql AS $$
DECLARE
  next_month     date := date_trunc('month', now()) + interval '1 month';
  next_month_end date := next_month + interval '1 month';
  suffix         text := to_char(next_month, 'YYYY_MM');
  tbl            text;
  partition_name text;
BEGIN
  FOREACH tbl IN ARRAY ARRAY['rsa_ticket_locations', 'rsa_team_locations'] LOOP
    partition_name := tbl || '_' || suffix;
    IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = partition_name) THEN
      EXECUTE format(
        'CREATE TABLE %I PARTITION OF %I FOR VALUES FROM (%L) TO (%L)',
        partition_name, tbl, next_month, next_month_end
      );
      EXECUTE format('CREATE INDEX ON %I (synced_at)', partition_name);
      IF tbl = 'rsa_ticket_locations' THEN
        EXECUTE format('CREATE INDEX ON %I (ticket_number)', partition_name);
      END IF;
      RAISE NOTICE 'Created partition %', partition_name;
    END IF;
  END LOOP;
END;
$$;

SELECT cron.schedule(
  'create_monthly_location_partitions',
  '0 0 25 * *',
  'SELECT public.create_monthly_location_partitions()'
);
